# Generated by Django 5.2 on 2025-10-25 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_connectionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('order', 'Order Placed'), ('status_change', 'Status Changed'), ('stock_out', 'Stock Out')], max_length=20),
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity sold/used')),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('used', 'Used/Consumed'), ('damaged', 'Damaged'), ('expired', 'Expired'), ('other', 'Other')], default='sale', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Optional notes about this stock out', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_stock_outs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='myapp.product')),
            ],
            options={
                'verbose_name': 'Stock Out',
                'verbose_name_plural': 'Stock Outs',
                'ordering': ['-created_at'],
            },
        ),
    ]
