# Generated by Django 5.2 on 2025-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('canned_goods', 'Canned Goods'), ('condiments', 'Condiments & Sauces'), ('dairy', 'Dairy Products'), ('snacks', 'Snacks & Chips'), ('instant_noodles', 'Instant Noodles'), ('rice_grains', 'Rice & Grains'), ('cooking_oil', 'Cooking Oil'), ('personal_care', 'Personal Care'), ('household', 'Household Items'), ('frozen', 'Frozen Foods'), ('bread_bakery', 'Bread & Bakery'), ('candy_sweets', 'Candy & Sweets'), ('cigarettes', 'Cigarettes & Tobacco'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('bottle', 'Bottle'), ('can', 'Can'), ('sachet', 'Sachet'), ('bag', 'Bag'), ('dozen', 'Dozen')], default='pcs', max_length=50),
        ),
    ]
