# Generated by Django 5.2 on 2025-10-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_supplierproduct_category_alter_supplierproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('bottle', 'Bottle'), ('can', 'Can'), ('sachet', 'Sachet'), ('bag', 'Bag'), ('dozen', 'Dozen')], default='pcs', max_length=50),
        ),
    ]
