# Generated by Django 5.2 on 2025-10-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('bank_transfer', 'Bank Transfer')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='stockout',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('bank_transfer', 'Bank Transfer')], default='cod', help_text='Payment method used for this transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='stockout',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash'), ('paymaya', 'PayMaya'), ('bank_transfer', 'Bank Transfer')], default='cod', help_text='Payment method for this order', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20),
        ),
    ]
