# Generated by Django 5.2 on 2025-10-31 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order_payment_method_order_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Has the supplier verified receiving this payment?'),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Supplier who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was verified by supplier', null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Has the supplier verified receiving this payment?'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Supplier who verified the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='verified_date',
            field=models.DateTimeField(blank=True, help_text='Date when payment was verified by supplier', null=True),
        ),
    ]
