# Generated by Django 5.2 on 2025-11-01 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order_payment_verified_order_verified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcash_number', models.CharField(blank=True, help_text='GCash mobile number for receiving payments', max_length=20, null=True)),
                ('gcash_account_name', models.CharField(blank=True, help_text='Name registered with GCash account', max_length=100, null=True)),
                ('paymaya_number', models.CharField(blank=True, help_text='PayMaya mobile number for receiving payments', max_length=20, null=True)),
                ('paymaya_account_name', models.CharField(blank=True, help_text='Name registered with PayMaya account', max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank (e.g., BDO, BPI, Metrobank)', max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, help_text='Account holder name as registered with the bank', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Additional instructions or notes for payment (e.g., branch, reference format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(help_text='Supplier user account', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Payment Information',
                'verbose_name_plural': 'Supplier Payment Information',
            },
        ),
    ]
