# Generated by Django 5.2 on 2025-11-01 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_supplierpaymentinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='delivery_status',
            field=models.CharField(choices=[('not_shipped', 'Not Yet Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='not_shipped', help_text='Current stage of the delivery/shipment', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='delivery_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time delivery status was updated', null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current stage of the order transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='order_status_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time order status was updated', null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
