# Generated by Django 5.2 on 2025-11-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_supplierorder_delivery_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='myapp.supplierorder')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('user1', 'user2', 'related_order')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Message subject (optional)', max_length=200)),
                ('body', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Has the recipient read this message?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When was this message read?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this message', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, help_text='Order this message is about', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='myapp.supplierorder')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='myapp_messa_recipie_9bc02d_idx'), models.Index(fields=['sender', 'recipient', '-created_at'], name='myapp_messa_sender__13be16_idx'), models.Index(fields=['related_order', '-created_at'], name='myapp_messa_related_8be642_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('delivery_shipped', 'Delivery Shipped'), ('delivery_out', 'Out for Delivery'), ('delivery_delivered', 'Delivery Delivered'), ('payment_paid', 'Payment Marked as Paid'), ('payment_verified', 'Payment Verified'), ('stock_low', 'Low Stock Alert'), ('stock_out', 'Out of Stock Alert'), ('new_message', 'New Message'), ('system', 'System Notification')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('is_read', models.BooleanField(default=False, help_text='Has the user read this notification?')),
                ('read_at', models.DateTimeField(blank=True, help_text='When was this notification read?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.supplierorder')),
                ('related_product', models.ForeignKey(blank=True, help_text='Related product if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.supplierproduct')),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='myapp_notif_recipie_057d22_idx'), models.Index(fields=['recipient', 'is_read'], name='myapp_notif_recipie_a39187_idx')],
            },
        ),
    ]
