# Generated by Django 5.2.7 on 2025-11-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='inventory_updated',
            field=models.BooleanField(default=False, help_text='Has inventory been updated for this order?'),
        ),
    ]
