# Generated by Django 5.2.7 on 2025-11-15 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_inventory_updated_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='business_address',
            field=models.TextField(blank=True, default='', help_text='Complete business address'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Business permit or certificate upload', null=True, upload_to='supplier_documents/'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='products_supplied',
            field=models.CharField(choices=[('beverages', 'Beverages'), ('canned_goods', 'Canned Goods'), ('condiments', 'Condiments & Sauces'), ('dairy', 'Dairy Products'), ('snacks', 'Snacks & Chips'), ('instant_noodles', 'Instant Noodles'), ('rice_grains', 'Rice & Grains'), ('cooking_oil', 'Cooking Oil'), ('personal_care', 'Personal Care'), ('household', 'Household Items'), ('frozen', 'Frozen Foods'), ('bread_bakery', 'Bread & Bakery'), ('candy_sweets', 'Candy & Sweets'), ('cigarettes', 'Cigarettes & Tobacco'), ('other', 'Other')], default='other', help_text='Type of products supplied', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this user was approved', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this user has been approved by admin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('bottle', 'Bottle'), ('can', 'Can'), ('sachet', 'Sachet'), ('bag', 'Bag'), ('sack', 'Sack'), ('dozen', 'Dozen')], default='pcs', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilogram'), ('g', 'Gram'), ('liter', 'Liter'), ('ml', 'Milliliter'), ('bottle', 'Bottle'), ('can', 'Can'), ('sachet', 'Sachet'), ('bag', 'Bag'), ('sack', 'Sack'), ('dozen', 'Dozen')], default='pcs', max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='Name of the store or business', max_length=200)),
                ('store_address', models.TextField(help_text='Complete store address/location')),
                ('store_type', models.CharField(choices=[('sari_sari', 'Sari-Sari Store'), ('grocery', 'Grocery Store'), ('mini_mart', 'Mini Mart'), ('convenience', 'Convenience Store'), ('supermarket', 'Supermarket'), ('other', 'Other')], default='sari_sari', help_text='Type of store', max_length=50)),
                ('business_permit', models.FileField(blank=True, help_text='Business permit or proof of registration', null=True, upload_to='owner_documents/')),
                ('contact_person', models.CharField(help_text='Primary contact person', max_length=200)),
                ('contact_phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('contact_email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Owner Profile',
                'verbose_name_plural': 'Business Owner Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
