# Generated by Django 5.2.7 on 2025-11-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_supplierprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Date when the product expires', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(blank=True, help_text='Date when the product was manufactured', null=True),
        ),
    ]
