# Generated by Django 5.2.7 on 2025-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_add_product_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Date when the product expires', null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='manufactured_date',
            field=models.DateField(blank=True, help_text='Date when the product was manufactured', null=True),
        ),
    ]
